alter table borrower
    add column email varchar(255);

alter table email_verification
    drop constraint email_verification_purpose_check;

alter table email_verification
    add constraint email_verification_purpose_check
        check (purpose in ('SIGNUP', 'PASSWORD_RESET', 'EMAIL_CHANGE', 'BORROW'));

create table borrow_email_verification_token
(
    id         bigint generated by default as identity primary key,
    created_at timestamp(6)  not null,
    updated_at timestamp(6)  not null,
    email      varchar(255)  not null unique,
    token_hash varchar(255)  not null unique,
    expires_at timestamp(6)  not null
);
