-- =========================================
-- 0) Extension / type (trgm objects depend on this)
-- =========================================
CREATE EXTENSION IF NOT EXISTS pg_trgm;


-- =========================================
-- 1) Base tables (no FK dependencies)
-- =========================================

create table signup_token
(
    code_verified_at timestamp(6),
    created_at       timestamp(6) not null,
    expires_at       timestamp(6) not null,
    signup_token_id  bigint generated by default as identity
        primary key,
    updated_at       timestamp(6) not null,
    used_at          timestamp(6),
    email            varchar(255) not null
        unique,
    token_hash       varchar(255) not null
        unique
);



create index idx_signup_token_email
    on signup_token (email);


create table borrower
(
    borrower_id              bigint generated by default as identity
        primary key,
    created_at               timestamp(6) not null,
    updated_at               timestamp(6) not null,
    name                     varchar(255) not null,
    phone                    varchar(255) not null,
    additional_borrower_info jsonb
);


create table organization
(
    created_at        timestamp(6) not null,
    last_login_at     timestamp(6),
    organization_id   bigint generated by default as identity
        primary key,
    updated_at        timestamp(6) not null,
    status            varchar(20)  not null
        constraint organization_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'SUSPENDED'::character varying, 'PENDING'::character varying])::text[])),
    profile_image_key varchar(500),
    admin_code_hash   varchar(255) not null,
    email             varchar(255) not null
        unique,
    name              varchar(255),
    password_hash     varchar(255) not null,
    search_key        varchar(255)
        unique
);

create table email_verification
(
    failed_attempts       integer      not null,
    created_at            timestamp(6) not null,
    email_verification_id bigint generated by default as identity
        primary key,
    expires_at            timestamp(6) not null,
    updated_at            timestamp(6) not null,
    verified_at           timestamp(6),
    purpose               varchar(30)  not null
        constraint email_verification_purpose_check
            check ((purpose)::text = ANY
                   ((ARRAY ['SIGNUP'::character varying, 'PASSWORD_RESET'::character varying, 'EMAIL_CHANGE'::character varying])::text[])),
    code                  varchar(255) not null,
    email                 varchar(255) not null,
    unique (email, purpose)
);



-- =========================================
-- 2) Tables that depend on organization
-- =========================================

create table password_reset_token
(
    created_at              timestamp(6) not null,
    expires_at              timestamp(6) not null,
    organization_id         bigint       not null
        constraint fkr77gmrikpu98hs4pry8vjqphr
            references organization,
    password_reset_token_id bigint generated by default as identity
        primary key,
    updated_at              timestamp(6) not null,
    used_at                 timestamp(6),
    token_hash              varchar(255) not null
        unique
);

create index idx_password_reset_token_org
    on password_reset_token (organization_id);

create unique index uk_password_reset_token_hash
    on password_reset_token (token_hash);


-- =========================================
-- 3) Item domain tables (org -> item -> item_borrower_field / item_unit)
-- =========================================

create table item
(
    available_quantity        integer      not null,
    is_active                 boolean      not null,
    rental_duration           integer      not null,
    total_quantity            integer      not null,
    use_message_alarm_service boolean      not null,
    created_at                timestamp(6) not null,
    item_id                   bigint generated by default as identity
        primary key,
    organization_id           bigint       not null
        constraint fk9ib7witqkp6wfpelwcyunsyc5
            references organization,
    updated_at                timestamp(6) not null,
    item_management_type      varchar(20)  not null
        constraint item_item_management_type_check
            check ((item_management_type)::text = ANY
                   ((ARRAY ['NON_UNIT'::character varying, 'UNIT'::character varying])::text[])),
    description               text,
    guaranteed_goods          varchar(255),
    name                      varchar(255) not null,
    public_id                 varchar(255) not null
        unique
);

create table item_borrower_field
(
    is_required            boolean      not null,
    sort_order             integer      not null,
    created_at             timestamp(6) not null,
    item_borrower_field_id bigint generated by default as identity
        primary key,
    item_id                bigint       not null
        constraint fk1qs39t13nv8g9rs0457o4as14
            references item,
    updated_at             timestamp(6) not null,
    label                  varchar(255) not null
);


create table item_unit
(
    created_at   timestamp(6) not null,
    item_id      bigint       not null
        constraint fkl1tq5iwe7lbc4ply3ofnake7l
            references item,
    item_unit_id bigint generated by default as identity
        primary key,
    updated_at   timestamp(6) not null,
    status       varchar(20)  not null
        constraint item_unit_status_check
            check ((status)::text = ANY
                   ((ARRAY ['AVAILABLE'::character varying, 'RENTAL_PENDING'::character varying, 'RENTED'::character varying, 'LOST'::character varying, 'BROKEN'::character varying, 'INACTIVE'::character varying])::text[])),
    label        varchar(255) not null,
    unique (item_id, label)
);


-- =========================================
-- 4) Rental domain tables (org/borrower -> rental -> children)
-- =========================================
create table rental
(
    due_date        date,
    borrower_id     bigint       not null
        unique
        constraint fkfvgfssyj6sd5e4u0ly6ho98uk
            references borrower,
    created_at      timestamp(6) not null,
    decided_at      timestamp(6),
    organization_id bigint       not null
        constraint fk7ems007np38dlajwrny55cay9
            references organization,
    rental_id       bigint generated by default as identity
        primary key,
    requested_at    timestamp(6) not null,
    returned_at     timestamp(6),
    updated_at      timestamp(6) not null,
    status          varchar(20)  not null
        constraint rental_status_check
            check ((status)::text = ANY
                   ((ARRAY ['REQUESTED'::character varying, 'RENTED'::character varying, 'REJECTED'::character varying, 'RETURNED'::character varying])::text[])),
    decided_by      varchar(255),
    public_id       varchar(255) not null
        unique,
    request_note varchar(100),
    received_by     varchar(255)
);

create table rental_item
(
    created_at     timestamp(6) not null,
    item_id        bigint       not null
        constraint fkdc8ytutqhpmkum82y1970ln2y
            references item,
    rental_id      bigint       not null
        constraint fka20tqix3c9aesqmluuq9lkn9b
            references rental,
    rental_item_id bigint generated by default as identity
        primary key,
    updated_at     timestamp(6) not null
);

create table rental_item_unit
(
    created_at     timestamp(6) not null,
    rental_id      bigint       not null
        constraint fkfc43dkgoclktdwvi5e4057pel
            references rental,
    rental_unit_id bigint generated by default as identity
        primary key,
    unit_id        bigint       not null
        constraint fk3tex62vev051ric7yx8ruysml
            references item_unit,
    updated_at     timestamp(6) not null
);

create table admin_code_verification_token
(
    expires_at      timestamp(6) not null,
    id              bigint generated by default as identity
        primary key,
    organization_id bigint       not null
        constraint fkq4hrsw8t2aoqgs0a0d8qbbcjk
            references organization,
    used_at         timestamp(6),
    purpose         varchar(255) not null
        constraint admin_code_verification_token_purpose_check
            check ((purpose)::text = ANY
                   ((ARRAY ['ORGANIZATION_UPDATE'::character varying, 'ITEM_UPDATE'::character varying, 'IMMEDIATE_APPROVAL'::character varying])::text[])),
    token_hash      varchar(255) not null
        constraint uk_admin_code_verification_token_hash
            unique,
    constraint uk_admin_code_verification_token_org_purpose
        unique (organization_id, purpose)
);

create table message_history
(
    id           bigserial
        primary key,
    rental_id    bigint       not null
        constraint fk_message_history_rental
            references rental,
    recipient    varchar(255),
    message_type varchar(255) not null,
    status       varchar(255) not null,
    content      text,
    sent_date    date,
    created_at   timestamp(6) not null,
    updated_at   timestamp(6) not null
);

create table phone_verification
(
    id                           varchar(255) not null
        primary key,
    created_at                   timestamp(6) not null,
    updated_at                   timestamp(6) not null,
    code_hash                    varchar(255) not null,
    expires_at                   timestamp(6) not null,
    failed_attempts              integer      not null,
    last_attempt_at              timestamp(6),
    phone                        varchar(255) not null,
    purpose                      varchar(255) not null
        constraint phone_verification_purpose_check
            check ((purpose)::text = 'BORROW'::text),
    request_attempts             integer      not null,
    request_lock_expiration      timestamp(6),
    verification_lock_expiration timestamp(6),
    verified_at                  timestamp(6),
    constraint uk_phone_verification_phone_purpose
        unique (phone, purpose)
);

create table phone_verification_token
(
    id                    varchar(255) not null
        primary key,
    created_at            timestamp(6) not null,
    updated_at            timestamp(6) not null,
    expires_at            timestamp(6) not null,
    token_hash            varchar(255) not null,
    phone_verification_id varchar(255) not null
        constraint uktjuhwcx07ajyusyysvlgtm2ei
            unique
        constraint fkly6qu2uggj8l64las63k8mf2s
            references phone_verification
);