create table refresh_token
(
    created_at       timestamp(6) not null,
    expires_at       timestamp(6) not null,
    refresh_token_id bigint generated by default as identity
        primary key,
    updated_at       timestamp(6) not null,
    email            varchar(255) not null,
    token_value      varchar(500) not null
        constraint uk_refresh_token_value
            unique
);

create index idx_refresh_token_email
    on refresh_token (email);
