alter table organization
    add column withdrawn_at timestamp(6);

alter table organization
    drop constraint organization_status_check;

alter table organization
    add constraint organization_status_check
        check ((status)::text = any
               ((array ['ACTIVE'::character varying, 'SUSPENDED'::character varying, 'PENDING'::character varying, 'WITHDRAWN'::character varying])::text[]));

create table withdrawal_feedback
(
    created_at             timestamp(6) not null,
    organization_id        bigint       not null
        constraint fk_withdrawal_feedback_organization
            references organization,
    updated_at             timestamp(6) not null,
    withdrawal_feedback_id bigint generated by default as identity
        primary key,
    other_reason           varchar(200)
);

create index idx_withdrawal_feedback_organization
    on withdrawal_feedback (organization_id);

create table withdrawal_feedback_reason
(
    withdrawal_feedback_id        bigint      not null
        constraint fk_withdrawal_feedback_reason_feedback
            references withdrawal_feedback,
    withdrawal_feedback_reason_id bigint generated by default as identity
        primary key,
    reason_code                   varchar(50) not null
        constraint withdrawal_feedback_reason_code_check
            check ((reason_code)::text = any
                   ((array ['ORG_CLOSED'::character varying,
                            'NO_LONGER_OPERATING_RENTAL'::character varying,
                            'MOVED_TO_OTHER_SERVICE'::character varying,
                            'PRIVACY_CONCERN'::character varying,
                            'SERVICE_UNSATISFIED'::character varying,
                            'MISSING_FEATURE'::character varying,
                            'LOW_USAGE'::character varying,
                            'OTHER'::character varying])::text[]))
);

create index idx_withdrawal_feedback_reason_feedback
    on withdrawal_feedback_reason (withdrawal_feedback_id);
