create table password_verification_token
(
    password_verification_token_id bigint generated by default as identity
        primary key,
    organization_id               bigint       not null
        constraint fk_password_verification_token_organization
            references organization,
    purpose                       varchar(30)  not null,
    token_hash                    varchar(255) not null,
    expires_at                    timestamp(6) not null,
    used_at                       timestamp(6),
    created_at                    timestamp(6) not null,
    updated_at                    timestamp(6) not null,
    constraint uk_password_verification_token_org_purpose
        unique (organization_id, purpose)
);
