INSERT INTO organization (created_at, updated_at, admin_code_hash, email, password_hash, name,
                          status, search_key)
VALUES (NOW(), NOW(), 'hash_1', 'cse_student@retrivr.com', 'pw_hash_1', '컴퓨터공학과 학생회', 'ACTIVE','org_cse_1'),
       (NOW(), NOW(), 'hash_2', 'me_student@retrivr.com', 'pw_hash_2', '기계공학과 학생회', 'ACTIVE','org_me_2'),
       (NOW(), NOW(), 'hash_3', 'ee_student@retrivr.com', 'pw_hash_3', '전자공학과 학생회', 'ACTIVE','org_ee_3'),
       (NOW(), NOW(), 'hash_4', 'biz_student@retrivr.com', 'pw_hash_4', '경영학과 학생회', 'ACTIVE',        'org_biz_4'),
       (NOW(), NOW(), 'hash_5', 'design_student@retrivr.com', 'pw_hash_5', '디자인학과 학생회', 'ACTIVE',      'org_design_5'),
       (NOW(), NOW(), 'hash_6', 'club_dev@retrivr.com', 'pw_hash_6', '개발 동아리 CODE', 'ACTIVE',        'org_dev_6'),
       (NOW(), NOW(), 'hash_7', 'club_ai@retrivr.com', 'pw_hash_7', 'AI 연구 동아리', 'ACTIVE',       'org_ai_7'),
       (NOW(), NOW(), 'hash_8', 'club_music@retrivr.com', 'pw_hash_8', '음악 동아리 SOUND', 'ACTIVE',        'org_music_8'),
       (NOW(), NOW(), 'hash_9', 'club_photo@retrivr.com', 'pw_hash_9', '사진 동아리 FRAME', 'ACTIVE',        'org_photo_9'),
       (NOW(), NOW(), 'hash_10', 'club_sports@retrivr.com', 'pw_hash_10', '체육 동아리 ACTIVE', 'ACTIVE',        'org_sports_10'),
       (NOW(), NOW(), 'hash_11', 'council_main@retrivr.com', 'pw_hash_11', '총학생회', 'ACTIVE',        'org_council_11'),
       (NOW(), NOW(), 'hash_12', 'council_event@retrivr.com', 'pw_hash_12', '학생회 행사부', 'ACTIVE',      'org_event_12'),
       (NOW(), NOW(), 'hash_13', 'council_media@retrivr.com', 'pw_hash_13', '학생회 미디어팀', 'ACTIVE',      'org_media_13'),
       (NOW(), NOW(), 'hash_14', 'startup_team@retrivr.com', 'pw_hash_14', '창업 동아리 STARTUP',       'ACTIVE', 'org_startup_14'),
       (NOW(), NOW(), 'hash_15', 'study_backend@retrivr.com', 'pw_hash_15', '백엔드 스터디', 'ACTIVE',       'org_backend_15'),
       (NOW(), NOW(), 'hash_16', 'study_frontend@retrivr.com', 'pw_hash_16', '프론트엔드 스터디', 'ACTIVE',       'org_frontend_16'),
       (NOW(), NOW(), 'hash_17', 'study_algo@retrivr.com', 'pw_hash_17', '알고리즘 스터디', 'ACTIVE',       'org_algo_17'),
       (NOW(), NOW(), 'hash_18', 'lab_robot@retrivr.com', 'pw_hash_18', '로봇 연구실', 'ACTIVE',     'org_robot_18'),
       (NOW(), NOW(), 'hash_19', 'lab_iot@retrivr.com', 'pw_hash_19', 'IoT 연구실', 'ACTIVE',    'org_iot_19'),
       (NOW(), NOW(), 'hash_20', 'lab_data@retrivr.com', 'pw_hash_20', '데이터 분석 연구실', 'ACTIVE',    'org_data_20');


-- Items + Item Units Mock Data (with public_id, synced)

INSERT INTO item (
    public_id,
    created_at, updated_at,
    available_quantity, total_quantity,
    description, guaranteed_goods,
    is_active, item_management_type,
    name, rental_duration,
    use_message_alarm_service,
    organization_id
) VALUES
      ('ITM-O01-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 1),
      ('ITM-O01-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 1),
      ('ITM-O01-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 1),
      ('ITM-O01-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 1),
      ('ITM-O01-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 1),
      ('ITM-O01-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 1),
      ('ITM-O01-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 1),
      ('ITM-O01-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 1),
      ('ITM-O01-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 1),
      ('ITM-O01-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 1),
      ('ITM-O02-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 2),
      ('ITM-O02-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 2),
      ('ITM-O02-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 2),
      ('ITM-O02-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 2),
      ('ITM-O02-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 2),
      ('ITM-O02-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 2),
      ('ITM-O02-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 2),
      ('ITM-O02-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 2),
      ('ITM-O02-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 2),
      ('ITM-O02-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 2),
      ('ITM-O03-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 3),
      ('ITM-O03-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 3),
      ('ITM-O03-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 3),
      ('ITM-O03-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 3),
      ('ITM-O03-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 3),
      ('ITM-O03-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 3),
      ('ITM-O03-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 3),
      ('ITM-O03-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 3),
      ('ITM-O03-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 3),
      ('ITM-O03-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 3),
      ('ITM-O04-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 4),
      ('ITM-O04-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 4),
      ('ITM-O04-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 4),
      ('ITM-O04-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 4),
      ('ITM-O04-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 4),
      ('ITM-O04-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 4),
      ('ITM-O04-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 4),
      ('ITM-O04-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 4),
      ('ITM-O04-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 4),
      ('ITM-O04-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 4),
      ('ITM-O05-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 5),
      ('ITM-O05-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 5),
      ('ITM-O05-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 5),
      ('ITM-O05-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 5),
      ('ITM-O05-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 5),
      ('ITM-O05-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 5),
      ('ITM-O05-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 5),
      ('ITM-O05-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 5),
      ('ITM-O05-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 5),
      ('ITM-O05-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 5),
      ('ITM-O06-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 6),
      ('ITM-O06-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 6),
      ('ITM-O06-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 6),
      ('ITM-O06-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 6),
      ('ITM-O06-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 6),
      ('ITM-O06-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 6),
      ('ITM-O06-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 6),
      ('ITM-O06-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 6),
      ('ITM-O06-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 6),
      ('ITM-O06-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 6),
      ('ITM-O07-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 7),
      ('ITM-O07-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 7),
      ('ITM-O07-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 7),
      ('ITM-O07-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 7),
      ('ITM-O07-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 7),
      ('ITM-O07-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 7),
      ('ITM-O07-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 7),
      ('ITM-O07-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 7),
      ('ITM-O07-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 7),
      ('ITM-O07-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 7),
      ('ITM-O08-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 8),
      ('ITM-O08-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 8),
      ('ITM-O08-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 8),
      ('ITM-O08-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 8),
      ('ITM-O08-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 8),
      ('ITM-O08-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 8),
      ('ITM-O08-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 8),
      ('ITM-O08-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 8),
      ('ITM-O08-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 8),
      ('ITM-O08-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 8),
      ('ITM-O09-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 9),
      ('ITM-O09-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 9),
      ('ITM-O09-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 9),
      ('ITM-O09-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 9),
      ('ITM-O09-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 9),
      ('ITM-O09-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 9),
      ('ITM-O09-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 9),
      ('ITM-O09-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 9),
      ('ITM-O09-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 9),
      ('ITM-O09-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 9),
      ('ITM-O10-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 10),
      ('ITM-O10-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 10),
      ('ITM-O10-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 10),
      ('ITM-O10-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 10),
      ('ITM-O10-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 10),
      ('ITM-O10-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 10),
      ('ITM-O10-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 10),
      ('ITM-O10-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 10),
      ('ITM-O10-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 10),
      ('ITM-O10-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 10),
      ('ITM-O11-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 11),
      ('ITM-O11-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 11),
      ('ITM-O11-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 11),
      ('ITM-O11-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 11),
      ('ITM-O11-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 11),
      ('ITM-O11-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 11),
      ('ITM-O11-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 11),
      ('ITM-O11-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 11),
      ('ITM-O11-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 11),
      ('ITM-O11-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 11),
      ('ITM-O12-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 12),
      ('ITM-O12-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 12),
      ('ITM-O12-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 12),
      ('ITM-O12-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 12),
      ('ITM-O12-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 12),
      ('ITM-O12-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 12),
      ('ITM-O12-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 12),
      ('ITM-O12-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 12),
      ('ITM-O12-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 12),
      ('ITM-O12-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 12),
      ('ITM-O13-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 13),
      ('ITM-O13-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 13),
      ('ITM-O13-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 13),
      ('ITM-O13-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 13),
      ('ITM-O13-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 13),
      ('ITM-O13-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 13),
      ('ITM-O13-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 13),
      ('ITM-O13-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 13),
      ('ITM-O13-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 13),
      ('ITM-O13-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 13),
      ('ITM-O14-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 14),
      ('ITM-O14-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 14),
      ('ITM-O14-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 14),
      ('ITM-O14-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 14),
      ('ITM-O14-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 14),
      ('ITM-O14-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 14),
      ('ITM-O14-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 14),
      ('ITM-O14-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 14),
      ('ITM-O14-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 14),
      ('ITM-O14-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 14),
      ('ITM-O15-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 15),
      ('ITM-O15-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 15),
      ('ITM-O15-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 15),
      ('ITM-O15-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 15),
      ('ITM-O15-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 15),
      ('ITM-O15-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 15),
      ('ITM-O15-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 15),
      ('ITM-O15-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 15),
      ('ITM-O15-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 15),
      ('ITM-O15-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 15),
      ('ITM-O16-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 16),
      ('ITM-O16-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 16),
      ('ITM-O16-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 16),
      ('ITM-O16-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 16),
      ('ITM-O16-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 16),
      ('ITM-O16-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 16),
      ('ITM-O16-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 16),
      ('ITM-O16-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 16),
      ('ITM-O16-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 16),
      ('ITM-O16-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 16),
      ('ITM-O17-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 17),
      ('ITM-O17-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 17),
      ('ITM-O17-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 17),
      ('ITM-O17-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 17),
      ('ITM-O17-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 17),
      ('ITM-O17-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 17),
      ('ITM-O17-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 17),
      ('ITM-O17-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 17),
      ('ITM-O17-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 17),
      ('ITM-O17-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 17),
      ('ITM-O18-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 18),
      ('ITM-O18-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 18),
      ('ITM-O18-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 18),
      ('ITM-O18-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 18),
      ('ITM-O18-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 18),
      ('ITM-O18-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 18),
      ('ITM-O18-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 18),
      ('ITM-O18-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 18),
      ('ITM-O18-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 18),
      ('ITM-O18-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 18),
      ('ITM-O19-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 19),
      ('ITM-O19-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 19),
      ('ITM-O19-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 19),
      ('ITM-O19-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 19),
      ('ITM-O19-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 19),
      ('ITM-O19-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 19),
      ('ITM-O19-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 19),
      ('ITM-O19-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 19),
      ('ITM-O19-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 19),
      ('ITM-O19-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 19),
      ('ITM-O20-001', NOW(), NOW(), 5, 5, '노트북 대여용', '학생증', true, 'UNIT', '노트북', 3, true, 20),
      ('ITM-O20-002', NOW(), NOW(), 10, 10, '우산 대여용', NULL, true, 'NON_UNIT', '우산', 3, false, 20),
      ('ITM-O20-003', NOW(), NOW(), 8, 8, '충전기 대여용', NULL, true, 'NON_UNIT', '충전기', 3, false, 20),
      ('ITM-O20-004', NOW(), NOW(), 3, 3, '카메라 대여용', '신분증', true, 'UNIT', '카메라', 3, true, 20),
      ('ITM-O20-005', NOW(), NOW(), 6, 6, '삼각대 대여용', NULL, true, 'UNIT', '삼각대', 3, false, 20),
      ('ITM-O20-006', NOW(), NOW(), 15, 15, '보드게임 대여용', NULL, true, 'NON_UNIT', '보드게임', 3, false, 20),
      ('ITM-O20-007', NOW(), NOW(), 4, 4, '마이크 대여용', '학생증', true, 'UNIT', '마이크', 3, true, 20),
      ('ITM-O20-008', NOW(), NOW(), 7, 7, '멀티탭 대여용', NULL, true, 'NON_UNIT', '멀티탭', 3, false, 20),
      ('ITM-O20-009', NOW(), NOW(), 2, 2, '빔프로젝터 대여용', '신분증', true, 'UNIT', '빔프로젝터', 3, true, 20),
      ('ITM-O20-010', NOW(), NOW(), 12, 12, '의자 대여용', NULL, true, 'NON_UNIT', '의자', 3, false, 20);

-- Item Units
INSERT INTO item_unit (
    created_at, updated_at,
    label, status, item_id
) VALUES
      (NOW(), NOW(), '노트-1-1', 'AVAILABLE', 1),
      (NOW(), NOW(), '노트-1-2', 'AVAILABLE', 1),
      (NOW(), NOW(), '노트-1-3', 'AVAILABLE', 1),
      (NOW(), NOW(), '노트-1-4', 'AVAILABLE', 1),
      (NOW(), NOW(), '노트-1-5', 'AVAILABLE', 1),
      (NOW(), NOW(), '카메-1-1', 'AVAILABLE', 4),
      (NOW(), NOW(), '카메-1-2', 'AVAILABLE', 4),
      (NOW(), NOW(), '카메-1-3', 'AVAILABLE', 4),
      (NOW(), NOW(), '삼각-1-1', 'AVAILABLE', 5),
      (NOW(), NOW(), '삼각-1-2', 'AVAILABLE', 5),
      (NOW(), NOW(), '삼각-1-3', 'AVAILABLE', 5),
      (NOW(), NOW(), '삼각-1-4', 'AVAILABLE', 5),
      (NOW(), NOW(), '삼각-1-5', 'AVAILABLE', 5),
      (NOW(), NOW(), '삼각-1-6', 'AVAILABLE', 5),
      (NOW(), NOW(), '마이-1-1', 'AVAILABLE', 7),
      (NOW(), NOW(), '마이-1-2', 'AVAILABLE', 7),
      (NOW(), NOW(), '마이-1-3', 'AVAILABLE', 7),
      (NOW(), NOW(), '마이-1-4', 'AVAILABLE', 7),
      (NOW(), NOW(), '빔프-1-1', 'AVAILABLE', 9),
      (NOW(), NOW(), '빔프-1-2', 'AVAILABLE', 9),
      (NOW(), NOW(), '노트-2-1', 'AVAILABLE', 11),
      (NOW(), NOW(), '노트-2-2', 'AVAILABLE', 11),
      (NOW(), NOW(), '노트-2-3', 'AVAILABLE', 11),
      (NOW(), NOW(), '노트-2-4', 'AVAILABLE', 11),
      (NOW(), NOW(), '노트-2-5', 'AVAILABLE', 11),
      (NOW(), NOW(), '카메-2-1', 'AVAILABLE', 14),
      (NOW(), NOW(), '카메-2-2', 'AVAILABLE', 14),
      (NOW(), NOW(), '카메-2-3', 'AVAILABLE', 14),
      (NOW(), NOW(), '삼각-2-1', 'AVAILABLE', 15),
      (NOW(), NOW(), '삼각-2-2', 'AVAILABLE', 15),
      (NOW(), NOW(), '삼각-2-3', 'AVAILABLE', 15),
      (NOW(), NOW(), '삼각-2-4', 'AVAILABLE', 15),
      (NOW(), NOW(), '삼각-2-5', 'AVAILABLE', 15),
      (NOW(), NOW(), '삼각-2-6', 'AVAILABLE', 15),
      (NOW(), NOW(), '마이-2-1', 'AVAILABLE', 17),
      (NOW(), NOW(), '마이-2-2', 'AVAILABLE', 17),
      (NOW(), NOW(), '마이-2-3', 'AVAILABLE', 17),
      (NOW(), NOW(), '마이-2-4', 'AVAILABLE', 17),
      (NOW(), NOW(), '빔프-2-1', 'AVAILABLE', 19),
      (NOW(), NOW(), '빔프-2-2', 'AVAILABLE', 19),
      (NOW(), NOW(), '노트-3-1', 'AVAILABLE', 21),
      (NOW(), NOW(), '노트-3-2', 'AVAILABLE', 21),
      (NOW(), NOW(), '노트-3-3', 'AVAILABLE', 21),
      (NOW(), NOW(), '노트-3-4', 'AVAILABLE', 21),
      (NOW(), NOW(), '노트-3-5', 'AVAILABLE', 21),
      (NOW(), NOW(), '카메-3-1', 'AVAILABLE', 24),
      (NOW(), NOW(), '카메-3-2', 'AVAILABLE', 24),
      (NOW(), NOW(), '카메-3-3', 'AVAILABLE', 24),
      (NOW(), NOW(), '삼각-3-1', 'AVAILABLE', 25),
      (NOW(), NOW(), '삼각-3-2', 'AVAILABLE', 25),
      (NOW(), NOW(), '삼각-3-3', 'AVAILABLE', 25),
      (NOW(), NOW(), '삼각-3-4', 'AVAILABLE', 25),
      (NOW(), NOW(), '삼각-3-5', 'AVAILABLE', 25),
      (NOW(), NOW(), '삼각-3-6', 'AVAILABLE', 25),
      (NOW(), NOW(), '마이-3-1', 'AVAILABLE', 27),
      (NOW(), NOW(), '마이-3-2', 'AVAILABLE', 27),
      (NOW(), NOW(), '마이-3-3', 'AVAILABLE', 27),
      (NOW(), NOW(), '마이-3-4', 'AVAILABLE', 27),
      (NOW(), NOW(), '빔프-3-1', 'AVAILABLE', 29),
      (NOW(), NOW(), '빔프-3-2', 'AVAILABLE', 29),
      (NOW(), NOW(), '노트-4-1', 'AVAILABLE', 31),
      (NOW(), NOW(), '노트-4-2', 'AVAILABLE', 31),
      (NOW(), NOW(), '노트-4-3', 'AVAILABLE', 31),
      (NOW(), NOW(), '노트-4-4', 'AVAILABLE', 31),
      (NOW(), NOW(), '노트-4-5', 'AVAILABLE', 31),
      (NOW(), NOW(), '카메-4-1', 'AVAILABLE', 34),
      (NOW(), NOW(), '카메-4-2', 'AVAILABLE', 34),
      (NOW(), NOW(), '카메-4-3', 'AVAILABLE', 34),
      (NOW(), NOW(), '삼각-4-1', 'AVAILABLE', 35),
      (NOW(), NOW(), '삼각-4-2', 'AVAILABLE', 35),
      (NOW(), NOW(), '삼각-4-3', 'AVAILABLE', 35),
      (NOW(), NOW(), '삼각-4-4', 'AVAILABLE', 35),
      (NOW(), NOW(), '삼각-4-5', 'AVAILABLE', 35),
      (NOW(), NOW(), '삼각-4-6', 'AVAILABLE', 35),
      (NOW(), NOW(), '마이-4-1', 'AVAILABLE', 37),
      (NOW(), NOW(), '마이-4-2', 'AVAILABLE', 37),
      (NOW(), NOW(), '마이-4-3', 'AVAILABLE', 37),
      (NOW(), NOW(), '마이-4-4', 'AVAILABLE', 37),
      (NOW(), NOW(), '빔프-4-1', 'AVAILABLE', 39),
      (NOW(), NOW(), '빔프-4-2', 'AVAILABLE', 39),
      (NOW(), NOW(), '노트-5-1', 'AVAILABLE', 41),
      (NOW(), NOW(), '노트-5-2', 'AVAILABLE', 41),
      (NOW(), NOW(), '노트-5-3', 'AVAILABLE', 41),
      (NOW(), NOW(), '노트-5-4', 'AVAILABLE', 41),
      (NOW(), NOW(), '노트-5-5', 'AVAILABLE', 41),
      (NOW(), NOW(), '카메-5-1', 'AVAILABLE', 44),
      (NOW(), NOW(), '카메-5-2', 'AVAILABLE', 44),
      (NOW(), NOW(), '카메-5-3', 'AVAILABLE', 44),
      (NOW(), NOW(), '삼각-5-1', 'AVAILABLE', 45),
      (NOW(), NOW(), '삼각-5-2', 'AVAILABLE', 45),
      (NOW(), NOW(), '삼각-5-3', 'AVAILABLE', 45),
      (NOW(), NOW(), '삼각-5-4', 'AVAILABLE', 45),
      (NOW(), NOW(), '삼각-5-5', 'AVAILABLE', 45),
      (NOW(), NOW(), '삼각-5-6', 'AVAILABLE', 45),
      (NOW(), NOW(), '마이-5-1', 'AVAILABLE', 47),
      (NOW(), NOW(), '마이-5-2', 'AVAILABLE', 47),
      (NOW(), NOW(), '마이-5-3', 'AVAILABLE', 47),
      (NOW(), NOW(), '마이-5-4', 'AVAILABLE', 47),
      (NOW(), NOW(), '빔프-5-1', 'AVAILABLE', 49),
      (NOW(), NOW(), '빔프-5-2', 'AVAILABLE', 49),
      (NOW(), NOW(), '노트-6-1', 'AVAILABLE', 51),
      (NOW(), NOW(), '노트-6-2', 'AVAILABLE', 51),
      (NOW(), NOW(), '노트-6-3', 'AVAILABLE', 51),
      (NOW(), NOW(), '노트-6-4', 'AVAILABLE', 51),
      (NOW(), NOW(), '노트-6-5', 'AVAILABLE', 51),
      (NOW(), NOW(), '카메-6-1', 'AVAILABLE', 54),
      (NOW(), NOW(), '카메-6-2', 'AVAILABLE', 54),
      (NOW(), NOW(), '카메-6-3', 'AVAILABLE', 54),
      (NOW(), NOW(), '삼각-6-1', 'AVAILABLE', 55),
      (NOW(), NOW(), '삼각-6-2', 'AVAILABLE', 55),
      (NOW(), NOW(), '삼각-6-3', 'AVAILABLE', 55),
      (NOW(), NOW(), '삼각-6-4', 'AVAILABLE', 55),
      (NOW(), NOW(), '삼각-6-5', 'AVAILABLE', 55),
      (NOW(), NOW(), '삼각-6-6', 'AVAILABLE', 55),
      (NOW(), NOW(), '마이-6-1', 'AVAILABLE', 57),
      (NOW(), NOW(), '마이-6-2', 'AVAILABLE', 57),
      (NOW(), NOW(), '마이-6-3', 'AVAILABLE', 57),
      (NOW(), NOW(), '마이-6-4', 'AVAILABLE', 57),
      (NOW(), NOW(), '빔프-6-1', 'AVAILABLE', 59),
      (NOW(), NOW(), '빔프-6-2', 'AVAILABLE', 59),
      (NOW(), NOW(), '노트-7-1', 'AVAILABLE', 61),
      (NOW(), NOW(), '노트-7-2', 'AVAILABLE', 61),
      (NOW(), NOW(), '노트-7-3', 'AVAILABLE', 61),
      (NOW(), NOW(), '노트-7-4', 'AVAILABLE', 61),
      (NOW(), NOW(), '노트-7-5', 'AVAILABLE', 61),
      (NOW(), NOW(), '카메-7-1', 'AVAILABLE', 64),
      (NOW(), NOW(), '카메-7-2', 'AVAILABLE', 64),
      (NOW(), NOW(), '카메-7-3', 'AVAILABLE', 64),
      (NOW(), NOW(), '삼각-7-1', 'AVAILABLE', 65),
      (NOW(), NOW(), '삼각-7-2', 'AVAILABLE', 65),
      (NOW(), NOW(), '삼각-7-3', 'AVAILABLE', 65),
      (NOW(), NOW(), '삼각-7-4', 'AVAILABLE', 65),
      (NOW(), NOW(), '삼각-7-5', 'AVAILABLE', 65),
      (NOW(), NOW(), '삼각-7-6', 'AVAILABLE', 65),
      (NOW(), NOW(), '마이-7-1', 'AVAILABLE', 67),
      (NOW(), NOW(), '마이-7-2', 'AVAILABLE', 67),
      (NOW(), NOW(), '마이-7-3', 'AVAILABLE', 67),
      (NOW(), NOW(), '마이-7-4', 'AVAILABLE', 67),
      (NOW(), NOW(), '빔프-7-1', 'AVAILABLE', 69),
      (NOW(), NOW(), '빔프-7-2', 'AVAILABLE', 69),
      (NOW(), NOW(), '노트-8-1', 'AVAILABLE', 71),
      (NOW(), NOW(), '노트-8-2', 'AVAILABLE', 71),
      (NOW(), NOW(), '노트-8-3', 'AVAILABLE', 71),
      (NOW(), NOW(), '노트-8-4', 'AVAILABLE', 71),
      (NOW(), NOW(), '노트-8-5', 'AVAILABLE', 71),
      (NOW(), NOW(), '카메-8-1', 'AVAILABLE', 74),
      (NOW(), NOW(), '카메-8-2', 'AVAILABLE', 74),
      (NOW(), NOW(), '카메-8-3', 'AVAILABLE', 74),
      (NOW(), NOW(), '삼각-8-1', 'AVAILABLE', 75),
      (NOW(), NOW(), '삼각-8-2', 'AVAILABLE', 75),
      (NOW(), NOW(), '삼각-8-3', 'AVAILABLE', 75),
      (NOW(), NOW(), '삼각-8-4', 'AVAILABLE', 75),
      (NOW(), NOW(), '삼각-8-5', 'AVAILABLE', 75),
      (NOW(), NOW(), '삼각-8-6', 'AVAILABLE', 75),
      (NOW(), NOW(), '마이-8-1', 'AVAILABLE', 77),
      (NOW(), NOW(), '마이-8-2', 'AVAILABLE', 77),
      (NOW(), NOW(), '마이-8-3', 'AVAILABLE', 77),
      (NOW(), NOW(), '마이-8-4', 'AVAILABLE', 77),
      (NOW(), NOW(), '빔프-8-1', 'AVAILABLE', 79),
      (NOW(), NOW(), '빔프-8-2', 'AVAILABLE', 79),
      (NOW(), NOW(), '노트-9-1', 'AVAILABLE', 81),
      (NOW(), NOW(), '노트-9-2', 'AVAILABLE', 81),
      (NOW(), NOW(), '노트-9-3', 'AVAILABLE', 81),
      (NOW(), NOW(), '노트-9-4', 'AVAILABLE', 81),
      (NOW(), NOW(), '노트-9-5', 'AVAILABLE', 81),
      (NOW(), NOW(), '카메-9-1', 'AVAILABLE', 84),
      (NOW(), NOW(), '카메-9-2', 'AVAILABLE', 84),
      (NOW(), NOW(), '카메-9-3', 'AVAILABLE', 84),
      (NOW(), NOW(), '삼각-9-1', 'AVAILABLE', 85),
      (NOW(), NOW(), '삼각-9-2', 'AVAILABLE', 85),
      (NOW(), NOW(), '삼각-9-3', 'AVAILABLE', 85),
      (NOW(), NOW(), '삼각-9-4', 'AVAILABLE', 85),
      (NOW(), NOW(), '삼각-9-5', 'AVAILABLE', 85),
      (NOW(), NOW(), '삼각-9-6', 'AVAILABLE', 85),
      (NOW(), NOW(), '마이-9-1', 'AVAILABLE', 87),
      (NOW(), NOW(), '마이-9-2', 'AVAILABLE', 87),
      (NOW(), NOW(), '마이-9-3', 'AVAILABLE', 87),
      (NOW(), NOW(), '마이-9-4', 'AVAILABLE', 87),
      (NOW(), NOW(), '빔프-9-1', 'AVAILABLE', 89),
      (NOW(), NOW(), '빔프-9-2', 'AVAILABLE', 89),
      (NOW(), NOW(), '노트-10-1', 'AVAILABLE', 91),
      (NOW(), NOW(), '노트-10-2', 'AVAILABLE', 91),
      (NOW(), NOW(), '노트-10-3', 'AVAILABLE', 91),
      (NOW(), NOW(), '노트-10-4', 'AVAILABLE', 91),
      (NOW(), NOW(), '노트-10-5', 'AVAILABLE', 91),
      (NOW(), NOW(), '카메-10-1', 'AVAILABLE', 94),
      (NOW(), NOW(), '카메-10-2', 'AVAILABLE', 94),
      (NOW(), NOW(), '카메-10-3', 'AVAILABLE', 94),
      (NOW(), NOW(), '삼각-10-1', 'AVAILABLE', 95),
      (NOW(), NOW(), '삼각-10-2', 'AVAILABLE', 95),
      (NOW(), NOW(), '삼각-10-3', 'AVAILABLE', 95),
      (NOW(), NOW(), '삼각-10-4', 'AVAILABLE', 95),
      (NOW(), NOW(), '삼각-10-5', 'AVAILABLE', 95),
      (NOW(), NOW(), '삼각-10-6', 'AVAILABLE', 95),
      (NOW(), NOW(), '마이-10-1', 'AVAILABLE', 97),
      (NOW(), NOW(), '마이-10-2', 'AVAILABLE', 97),
      (NOW(), NOW(), '마이-10-3', 'AVAILABLE', 97),
      (NOW(), NOW(), '마이-10-4', 'AVAILABLE', 97),
      (NOW(), NOW(), '빔프-10-1', 'AVAILABLE', 99),
      (NOW(), NOW(), '빔프-10-2', 'AVAILABLE', 99),
      (NOW(), NOW(), '노트-11-1', 'AVAILABLE', 101),
      (NOW(), NOW(), '노트-11-2', 'AVAILABLE', 101),
      (NOW(), NOW(), '노트-11-3', 'AVAILABLE', 101),
      (NOW(), NOW(), '노트-11-4', 'AVAILABLE', 101),
      (NOW(), NOW(), '노트-11-5', 'AVAILABLE', 101),
      (NOW(), NOW(), '카메-11-1', 'AVAILABLE', 104),
      (NOW(), NOW(), '카메-11-2', 'AVAILABLE', 104),
      (NOW(), NOW(), '카메-11-3', 'AVAILABLE', 104),
      (NOW(), NOW(), '삼각-11-1', 'AVAILABLE', 105),
      (NOW(), NOW(), '삼각-11-2', 'AVAILABLE', 105),
      (NOW(), NOW(), '삼각-11-3', 'AVAILABLE', 105),
      (NOW(), NOW(), '삼각-11-4', 'AVAILABLE', 105),
      (NOW(), NOW(), '삼각-11-5', 'AVAILABLE', 105),
      (NOW(), NOW(), '삼각-11-6', 'AVAILABLE', 105),
      (NOW(), NOW(), '마이-11-1', 'AVAILABLE', 107),
      (NOW(), NOW(), '마이-11-2', 'AVAILABLE', 107),
      (NOW(), NOW(), '마이-11-3', 'AVAILABLE', 107),
      (NOW(), NOW(), '마이-11-4', 'AVAILABLE', 107),
      (NOW(), NOW(), '빔프-11-1', 'AVAILABLE', 109),
      (NOW(), NOW(), '빔프-11-2', 'AVAILABLE', 109),
      (NOW(), NOW(), '노트-12-1', 'AVAILABLE', 111),
      (NOW(), NOW(), '노트-12-2', 'AVAILABLE', 111),
      (NOW(), NOW(), '노트-12-3', 'AVAILABLE', 111),
      (NOW(), NOW(), '노트-12-4', 'AVAILABLE', 111),
      (NOW(), NOW(), '노트-12-5', 'AVAILABLE', 111),
      (NOW(), NOW(), '카메-12-1', 'AVAILABLE', 114),
      (NOW(), NOW(), '카메-12-2', 'AVAILABLE', 114),
      (NOW(), NOW(), '카메-12-3', 'AVAILABLE', 114),
      (NOW(), NOW(), '삼각-12-1', 'AVAILABLE', 115),
      (NOW(), NOW(), '삼각-12-2', 'AVAILABLE', 115),
      (NOW(), NOW(), '삼각-12-3', 'AVAILABLE', 115),
      (NOW(), NOW(), '삼각-12-4', 'AVAILABLE', 115),
      (NOW(), NOW(), '삼각-12-5', 'AVAILABLE', 115),
      (NOW(), NOW(), '삼각-12-6', 'AVAILABLE', 115),
      (NOW(), NOW(), '마이-12-1', 'AVAILABLE', 117),
      (NOW(), NOW(), '마이-12-2', 'AVAILABLE', 117),
      (NOW(), NOW(), '마이-12-3', 'AVAILABLE', 117),
      (NOW(), NOW(), '마이-12-4', 'AVAILABLE', 117),
      (NOW(), NOW(), '빔프-12-1', 'AVAILABLE', 119),
      (NOW(), NOW(), '빔프-12-2', 'AVAILABLE', 119),
      (NOW(), NOW(), '노트-13-1', 'AVAILABLE', 121),
      (NOW(), NOW(), '노트-13-2', 'AVAILABLE', 121),
      (NOW(), NOW(), '노트-13-3', 'AVAILABLE', 121),
      (NOW(), NOW(), '노트-13-4', 'AVAILABLE', 121),
      (NOW(), NOW(), '노트-13-5', 'AVAILABLE', 121),
      (NOW(), NOW(), '카메-13-1', 'AVAILABLE', 124),
      (NOW(), NOW(), '카메-13-2', 'AVAILABLE', 124),
      (NOW(), NOW(), '카메-13-3', 'AVAILABLE', 124),
      (NOW(), NOW(), '삼각-13-1', 'AVAILABLE', 125),
      (NOW(), NOW(), '삼각-13-2', 'AVAILABLE', 125),
      (NOW(), NOW(), '삼각-13-3', 'AVAILABLE', 125),
      (NOW(), NOW(), '삼각-13-4', 'AVAILABLE', 125),
      (NOW(), NOW(), '삼각-13-5', 'AVAILABLE', 125),
      (NOW(), NOW(), '삼각-13-6', 'AVAILABLE', 125),
      (NOW(), NOW(), '마이-13-1', 'AVAILABLE', 127),
      (NOW(), NOW(), '마이-13-2', 'AVAILABLE', 127),
      (NOW(), NOW(), '마이-13-3', 'AVAILABLE', 127),
      (NOW(), NOW(), '마이-13-4', 'AVAILABLE', 127),
      (NOW(), NOW(), '빔프-13-1', 'AVAILABLE', 129),
      (NOW(), NOW(), '빔프-13-2', 'AVAILABLE', 129),
      (NOW(), NOW(), '노트-14-1', 'AVAILABLE', 131),
      (NOW(), NOW(), '노트-14-2', 'AVAILABLE', 131),
      (NOW(), NOW(), '노트-14-3', 'AVAILABLE', 131),
      (NOW(), NOW(), '노트-14-4', 'AVAILABLE', 131),
      (NOW(), NOW(), '노트-14-5', 'AVAILABLE', 131),
      (NOW(), NOW(), '카메-14-1', 'AVAILABLE', 134),
      (NOW(), NOW(), '카메-14-2', 'AVAILABLE', 134),
      (NOW(), NOW(), '카메-14-3', 'AVAILABLE', 134),
      (NOW(), NOW(), '삼각-14-1', 'AVAILABLE', 135),
      (NOW(), NOW(), '삼각-14-2', 'AVAILABLE', 135),
      (NOW(), NOW(), '삼각-14-3', 'AVAILABLE', 135),
      (NOW(), NOW(), '삼각-14-4', 'AVAILABLE', 135),
      (NOW(), NOW(), '삼각-14-5', 'AVAILABLE', 135),
      (NOW(), NOW(), '삼각-14-6', 'AVAILABLE', 135),
      (NOW(), NOW(), '마이-14-1', 'AVAILABLE', 137),
      (NOW(), NOW(), '마이-14-2', 'AVAILABLE', 137),
      (NOW(), NOW(), '마이-14-3', 'AVAILABLE', 137),
      (NOW(), NOW(), '마이-14-4', 'AVAILABLE', 137),
      (NOW(), NOW(), '빔프-14-1', 'AVAILABLE', 139),
      (NOW(), NOW(), '빔프-14-2', 'AVAILABLE', 139),
      (NOW(), NOW(), '노트-15-1', 'AVAILABLE', 141),
      (NOW(), NOW(), '노트-15-2', 'AVAILABLE', 141),
      (NOW(), NOW(), '노트-15-3', 'AVAILABLE', 141),
      (NOW(), NOW(), '노트-15-4', 'AVAILABLE', 141),
      (NOW(), NOW(), '노트-15-5', 'AVAILABLE', 141),
      (NOW(), NOW(), '카메-15-1', 'AVAILABLE', 144),
      (NOW(), NOW(), '카메-15-2', 'AVAILABLE', 144),
      (NOW(), NOW(), '카메-15-3', 'AVAILABLE', 144),
      (NOW(), NOW(), '삼각-15-1', 'AVAILABLE', 145),
      (NOW(), NOW(), '삼각-15-2', 'AVAILABLE', 145),
      (NOW(), NOW(), '삼각-15-3', 'AVAILABLE', 145),
      (NOW(), NOW(), '삼각-15-4', 'AVAILABLE', 145),
      (NOW(), NOW(), '삼각-15-5', 'AVAILABLE', 145),
      (NOW(), NOW(), '삼각-15-6', 'AVAILABLE', 145),
      (NOW(), NOW(), '마이-15-1', 'AVAILABLE', 147),
      (NOW(), NOW(), '마이-15-2', 'AVAILABLE', 147),
      (NOW(), NOW(), '마이-15-3', 'AVAILABLE', 147),
      (NOW(), NOW(), '마이-15-4', 'AVAILABLE', 147),
      (NOW(), NOW(), '빔프-15-1', 'AVAILABLE', 149),
      (NOW(), NOW(), '빔프-15-2', 'AVAILABLE', 149),
      (NOW(), NOW(), '노트-16-1', 'AVAILABLE', 151),
      (NOW(), NOW(), '노트-16-2', 'AVAILABLE', 151),
      (NOW(), NOW(), '노트-16-3', 'AVAILABLE', 151),
      (NOW(), NOW(), '노트-16-4', 'AVAILABLE', 151),
      (NOW(), NOW(), '노트-16-5', 'AVAILABLE', 151),
      (NOW(), NOW(), '카메-16-1', 'AVAILABLE', 154),
      (NOW(), NOW(), '카메-16-2', 'AVAILABLE', 154),
      (NOW(), NOW(), '카메-16-3', 'AVAILABLE', 154),
      (NOW(), NOW(), '삼각-16-1', 'AVAILABLE', 155),
      (NOW(), NOW(), '삼각-16-2', 'AVAILABLE', 155),
      (NOW(), NOW(), '삼각-16-3', 'AVAILABLE', 155),
      (NOW(), NOW(), '삼각-16-4', 'AVAILABLE', 155),
      (NOW(), NOW(), '삼각-16-5', 'AVAILABLE', 155),
      (NOW(), NOW(), '삼각-16-6', 'AVAILABLE', 155),
      (NOW(), NOW(), '마이-16-1', 'AVAILABLE', 157),
      (NOW(), NOW(), '마이-16-2', 'AVAILABLE', 157),
      (NOW(), NOW(), '마이-16-3', 'AVAILABLE', 157),
      (NOW(), NOW(), '마이-16-4', 'AVAILABLE', 157),
      (NOW(), NOW(), '빔프-16-1', 'AVAILABLE', 159),
      (NOW(), NOW(), '빔프-16-2', 'AVAILABLE', 159),
      (NOW(), NOW(), '노트-17-1', 'AVAILABLE', 161),
      (NOW(), NOW(), '노트-17-2', 'AVAILABLE', 161),
      (NOW(), NOW(), '노트-17-3', 'AVAILABLE', 161),
      (NOW(), NOW(), '노트-17-4', 'AVAILABLE', 161),
      (NOW(), NOW(), '노트-17-5', 'AVAILABLE', 161),
      (NOW(), NOW(), '카메-17-1', 'AVAILABLE', 164),
      (NOW(), NOW(), '카메-17-2', 'AVAILABLE', 164),
      (NOW(), NOW(), '카메-17-3', 'AVAILABLE', 164),
      (NOW(), NOW(), '삼각-17-1', 'AVAILABLE', 165),
      (NOW(), NOW(), '삼각-17-2', 'AVAILABLE', 165),
      (NOW(), NOW(), '삼각-17-3', 'AVAILABLE', 165),
      (NOW(), NOW(), '삼각-17-4', 'AVAILABLE', 165),
      (NOW(), NOW(), '삼각-17-5', 'AVAILABLE', 165),
      (NOW(), NOW(), '삼각-17-6', 'AVAILABLE', 165),
      (NOW(), NOW(), '마이-17-1', 'AVAILABLE', 167),
      (NOW(), NOW(), '마이-17-2', 'AVAILABLE', 167),
      (NOW(), NOW(), '마이-17-3', 'AVAILABLE', 167),
      (NOW(), NOW(), '마이-17-4', 'AVAILABLE', 167),
      (NOW(), NOW(), '빔프-17-1', 'AVAILABLE', 169),
      (NOW(), NOW(), '빔프-17-2', 'AVAILABLE', 169),
      (NOW(), NOW(), '노트-18-1', 'AVAILABLE', 171),
      (NOW(), NOW(), '노트-18-2', 'AVAILABLE', 171),
      (NOW(), NOW(), '노트-18-3', 'AVAILABLE', 171),
      (NOW(), NOW(), '노트-18-4', 'AVAILABLE', 171),
      (NOW(), NOW(), '노트-18-5', 'AVAILABLE', 171),
      (NOW(), NOW(), '카메-18-1', 'AVAILABLE', 174),
      (NOW(), NOW(), '카메-18-2', 'AVAILABLE', 174),
      (NOW(), NOW(), '카메-18-3', 'AVAILABLE', 174),
      (NOW(), NOW(), '삼각-18-1', 'AVAILABLE', 175),
      (NOW(), NOW(), '삼각-18-2', 'AVAILABLE', 175),
      (NOW(), NOW(), '삼각-18-3', 'AVAILABLE', 175),
      (NOW(), NOW(), '삼각-18-4', 'AVAILABLE', 175),
      (NOW(), NOW(), '삼각-18-5', 'AVAILABLE', 175),
      (NOW(), NOW(), '삼각-18-6', 'AVAILABLE', 175),
      (NOW(), NOW(), '마이-18-1', 'AVAILABLE', 177),
      (NOW(), NOW(), '마이-18-2', 'AVAILABLE', 177),
      (NOW(), NOW(), '마이-18-3', 'AVAILABLE', 177),
      (NOW(), NOW(), '마이-18-4', 'AVAILABLE', 177),
      (NOW(), NOW(), '빔프-18-1', 'AVAILABLE', 179),
      (NOW(), NOW(), '빔프-18-2', 'AVAILABLE', 179),
      (NOW(), NOW(), '노트-19-1', 'AVAILABLE', 181),
      (NOW(), NOW(), '노트-19-2', 'AVAILABLE', 181),
      (NOW(), NOW(), '노트-19-3', 'AVAILABLE', 181),
      (NOW(), NOW(), '노트-19-4', 'AVAILABLE', 181),
      (NOW(), NOW(), '노트-19-5', 'AVAILABLE', 181),
      (NOW(), NOW(), '카메-19-1', 'AVAILABLE', 184),
      (NOW(), NOW(), '카메-19-2', 'AVAILABLE', 184),
      (NOW(), NOW(), '카메-19-3', 'AVAILABLE', 184),
      (NOW(), NOW(), '삼각-19-1', 'AVAILABLE', 185),
      (NOW(), NOW(), '삼각-19-2', 'AVAILABLE', 185),
      (NOW(), NOW(), '삼각-19-3', 'AVAILABLE', 185),
      (NOW(), NOW(), '삼각-19-4', 'AVAILABLE', 185),
      (NOW(), NOW(), '삼각-19-5', 'AVAILABLE', 185),
      (NOW(), NOW(), '삼각-19-6', 'AVAILABLE', 185),
      (NOW(), NOW(), '마이-19-1', 'AVAILABLE', 187),
      (NOW(), NOW(), '마이-19-2', 'AVAILABLE', 187),
      (NOW(), NOW(), '마이-19-3', 'AVAILABLE', 187),
      (NOW(), NOW(), '마이-19-4', 'AVAILABLE', 187),
      (NOW(), NOW(), '빔프-19-1', 'AVAILABLE', 189),
      (NOW(), NOW(), '빔프-19-2', 'AVAILABLE', 189),
      (NOW(), NOW(), '노트-20-1', 'AVAILABLE', 191),
      (NOW(), NOW(), '노트-20-2', 'AVAILABLE', 191),
      (NOW(), NOW(), '노트-20-3', 'AVAILABLE', 191),
      (NOW(), NOW(), '노트-20-4', 'AVAILABLE', 191),
      (NOW(), NOW(), '노트-20-5', 'AVAILABLE', 191),
      (NOW(), NOW(), '카메-20-1', 'AVAILABLE', 194),
      (NOW(), NOW(), '카메-20-2', 'AVAILABLE', 194),
      (NOW(), NOW(), '카메-20-3', 'AVAILABLE', 194),
      (NOW(), NOW(), '삼각-20-1', 'AVAILABLE', 195),
      (NOW(), NOW(), '삼각-20-2', 'AVAILABLE', 195),
      (NOW(), NOW(), '삼각-20-3', 'AVAILABLE', 195),
      (NOW(), NOW(), '삼각-20-4', 'AVAILABLE', 195),
      (NOW(), NOW(), '삼각-20-5', 'AVAILABLE', 195),
      (NOW(), NOW(), '삼각-20-6', 'AVAILABLE', 195),
      (NOW(), NOW(), '마이-20-1', 'AVAILABLE', 197),
      (NOW(), NOW(), '마이-20-2', 'AVAILABLE', 197),
      (NOW(), NOW(), '마이-20-3', 'AVAILABLE', 197),
      (NOW(), NOW(), '마이-20-4', 'AVAILABLE', 197),
      (NOW(), NOW(), '빔프-20-1', 'AVAILABLE', 199),
      (NOW(), NOW(), '빔프-20-2', 'AVAILABLE', 199);

